import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  loadingScreen: {
    backgroundColor: 'white',
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    height: 750,
  },
  homeScreen: {
    backgroundColor: '#F2F2F2',
    flex: 1,
  },
  homeIcon: {
    width: 25,
    height: 25,
    top: 1.5,
  },
  homeTitle: {
    fontSize: 30,
    color: '#080961',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    height: 50,
    borderWidth: 0.5,
  },
  aboutMe: {
    width: 31,
    height: 31,
    top: 1,
    left: 105,
  },
  userCardContainer: {
    display: 'flex',
    alignItems: 'center',
    marginVertical: 5,
    borderColor: 'white',
    marginHorizontal: 5,
    width: '100%',
  },
  firstNameUserCard: {
    fontSize: 20,
    color: '#212121',
    fontWeight: '500',
    alignSelf: 'flex-start',
    bottom: 65,
    left: 118,
  },

  imageUserCard: {
    width: 69,
    height: 69,
    borderRadius: 150,
    bottom: 15,
    left: 25,
    alignSelf: 'flex-start',
  },
  emailUserCard: {
    fontSize: 16,
    color: '#242222',
    textAlign: 'left',
    bottom: 60,
    left: 14,
  },
  lineEmailUserCard: {
    borderWidth: 0.2,
    borderColor: '#080961',
    width: 1000,
    bottom: 30,
    marginTop: 15,
  },
  detailContainer: {
    flex: 1,
  },
  headerDetail: {
    alignSelf: 'center',
  },
  titleProfile: {
    alignSelf: 'center',
    color: 'white',
    fontSize: 36,
    top: 50,
  },
  imageUserDetail: {
    alignSelf: 'center',
    width: 210,
    height: 210,
    borderRadius: 250,
    top: 110,
  },
  borderImage: {
    backgroundColor: '#080961',
    position: 'absolute',
    alignSelf: 'center',
    borderRadius: 500,
    height: 380,
    width: 500,
    bottom: 450,
  },
  userNameContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    width: 250,
    left: 80,
    top: 150,
    gap: 10,
  },
  userNameDetail: {
    alignSelf: 'flex-start',
    textAlign: 'left',
    fontSize: 18,
    top: 7,
  },
  iconNameDetail: {
    width: 35,
    height: 35,
  },
  userEmailContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    top: 180,
    gap: 7,
    left: 70,
  },
  userEmailDetail: {
    alignSelf: 'flex-start',
    textAlign: 'left',
    fontSize: 18,
    top: 12,
  },
  iconEmailDetail: {
    width: 50,
    height: 50,
  },
  lineDetailName: {
    borderWidth: 0.2,
    borderColor: '#080961',
    width: 550,
    top: 50,
    right: 320,
  },
  lineDetailEmail: {
    borderWidth: 0.2,
    height: 0.1,
    borderColor: '#080961',
    width: 700,
    top: 60,
    right: 480,
  },
  roleContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    top: 200,
    left: 62,
  },
  roleDetail: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    fontSize: 18,
    color: 'gray',
    top: 25,
  },
  roleIcon: {
    width: 69,
    height: 69,
  },
  aboutMeContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerAboutMe: {
    fontSize: 30,
    marginTop: 50,
    textAlign: 'center',
    fontWeight: '500',
  },
  profilePic: {
    marginTop: 25,
    width: 220,
    height: 220,
    top: 3,
    borderRadius: 250,
  },
  profileBackground: {
    alignItems: 'center',
  },
  pictureBackground: {
    width: 240,
    height: 240,
    backgroundColor: '#080961',
    position: 'absolute',
    borderRadius: 250,
    top: 18,
  },
  subTitle: {
    fontWeight: 'normal',
    fontSize: 14,
    textAlign: 'center',
  },
  linkedinContainer: {
    flexDirection: 'row-reverse',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    top: 20,
    marginTop: 15,
    // width: 250,
    // borderWidth: 1,
  },
  linkedinTitle: {
    fontSize: 20,
    fontWeight: '400',
    color: 'black',
    top: 16,
  },
  githubTitle: {
    fontSize: 20,
    fontWeight: '400',
    color: 'black',
    top: 16,
    left: 22,
  },

  linkedinIcon: {
    width: 60,
    height: 60,
  },
  githubIcon: {
    width: 60,
    height: 60,
    left: 25,
  },
  userNameContainerHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
});
